//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace 测试用例.TestAte {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="tCheckDataTestAteSoap", Namespace="http://tempuri.org/")]
    public partial class tCheckDataTestAte : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckEmpOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllStationOperationCompleted;
        
        private System.Threading.SendOrPostCallback Check_Route_ATEOperationCompleted;
        
        private System.Threading.SendOrPostCallback INS_ATE_BackOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLineListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWOSnRuleOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertWipKeyPartsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEsnDataInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSnInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public tCheckDataTestAte() {
            this.Url = "http://172.16.173.76/SFIS_TEST/tCheckDataTestAte.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckEmpCompletedEventHandler CheckEmpCompleted;
        
        /// <remarks/>
        public event GetAllStationCompletedEventHandler GetAllStationCompleted;
        
        /// <remarks/>
        public event Check_Route_ATECompletedEventHandler Check_Route_ATECompleted;
        
        /// <remarks/>
        public event INS_ATE_BackCompletedEventHandler INS_ATE_BackCompleted;
        
        /// <remarks/>
        public event GetLineListCompletedEventHandler GetLineListCompleted;
        
        /// <remarks/>
        public event GetWOSnRuleCompletedEventHandler GetWOSnRuleCompleted;
        
        /// <remarks/>
        public event InsertWipKeyPartsCompletedEventHandler InsertWipKeyPartsCompleted;
        
        /// <remarks/>
        public event GetEsnDataInfoCompletedEventHandler GetEsnDataInfoCompleted;
        
        /// <remarks/>
        public event GetSnInfoCompletedEventHandler GetSnInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckEmp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckEmp(string EMP) {
            object[] results = this.Invoke("CheckEmp", new object[] {
                        EMP});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckEmpAsync(string EMP) {
            this.CheckEmpAsync(EMP, null);
        }
        
        /// <remarks/>
        public void CheckEmpAsync(string EMP, object userState) {
            if ((this.CheckEmpOperationCompleted == null)) {
                this.CheckEmpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckEmpOperationCompleted);
            }
            this.InvokeAsync("CheckEmp", new object[] {
                        EMP}, this.CheckEmpOperationCompleted, userState);
        }
        
        private void OnCheckEmpOperationCompleted(object arg) {
            if ((this.CheckEmpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckEmpCompleted(this, new CheckEmpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllStation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllStation(string woId) {
            object[] results = this.Invoke("GetAllStation", new object[] {
                        woId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllStationAsync(string woId) {
            this.GetAllStationAsync(woId, null);
        }
        
        /// <remarks/>
        public void GetAllStationAsync(string woId, object userState) {
            if ((this.GetAllStationOperationCompleted == null)) {
                this.GetAllStationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllStationOperationCompleted);
            }
            this.InvokeAsync("GetAllStation", new object[] {
                        woId}, this.GetAllStationOperationCompleted, userState);
        }
        
        private void OnGetAllStationOperationCompleted(object arg) {
            if ((this.GetAllStationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllStationCompleted(this, new GetAllStationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Check_Route_ATE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Check_Route_ATE(string DATA, string Route, string WO) {
            object[] results = this.Invoke("Check_Route_ATE", new object[] {
                        DATA,
                        Route,
                        WO});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Check_Route_ATEAsync(string DATA, string Route, string WO) {
            this.Check_Route_ATEAsync(DATA, Route, WO, null);
        }
        
        /// <remarks/>
        public void Check_Route_ATEAsync(string DATA, string Route, string WO, object userState) {
            if ((this.Check_Route_ATEOperationCompleted == null)) {
                this.Check_Route_ATEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheck_Route_ATEOperationCompleted);
            }
            this.InvokeAsync("Check_Route_ATE", new object[] {
                        DATA,
                        Route,
                        WO}, this.Check_Route_ATEOperationCompleted, userState);
        }
        
        private void OnCheck_Route_ATEOperationCompleted(object arg) {
            if ((this.Check_Route_ATECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Check_Route_ATECompleted(this, new Check_Route_ATECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INS_ATE_Back", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string INS_ATE_Back(string DATA, string Route, string EMP, string LINE) {
            object[] results = this.Invoke("INS_ATE_Back", new object[] {
                        DATA,
                        Route,
                        EMP,
                        LINE});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void INS_ATE_BackAsync(string DATA, string Route, string EMP, string LINE) {
            this.INS_ATE_BackAsync(DATA, Route, EMP, LINE, null);
        }
        
        /// <remarks/>
        public void INS_ATE_BackAsync(string DATA, string Route, string EMP, string LINE, object userState) {
            if ((this.INS_ATE_BackOperationCompleted == null)) {
                this.INS_ATE_BackOperationCompleted = new System.Threading.SendOrPostCallback(this.OnINS_ATE_BackOperationCompleted);
            }
            this.InvokeAsync("INS_ATE_Back", new object[] {
                        DATA,
                        Route,
                        EMP,
                        LINE}, this.INS_ATE_BackOperationCompleted, userState);
        }
        
        private void OnINS_ATE_BackOperationCompleted(object arg) {
            if ((this.INS_ATE_BackCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.INS_ATE_BackCompleted(this, new INS_ATE_BackCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLineList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetLineList() {
            object[] results = this.Invoke("GetLineList", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetLineListAsync() {
            this.GetLineListAsync(null);
        }
        
        /// <remarks/>
        public void GetLineListAsync(object userState) {
            if ((this.GetLineListOperationCompleted == null)) {
                this.GetLineListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLineListOperationCompleted);
            }
            this.InvokeAsync("GetLineList", new object[0], this.GetLineListOperationCompleted, userState);
        }
        
        private void OnGetLineListOperationCompleted(object arg) {
            if ((this.GetLineListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLineListCompleted(this, new GetLineListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWOSnRule", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetWOSnRule(string woId) {
            object[] results = this.Invoke("GetWOSnRule", new object[] {
                        woId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetWOSnRuleAsync(string woId) {
            this.GetWOSnRuleAsync(woId, null);
        }
        
        /// <remarks/>
        public void GetWOSnRuleAsync(string woId, object userState) {
            if ((this.GetWOSnRuleOperationCompleted == null)) {
                this.GetWOSnRuleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWOSnRuleOperationCompleted);
            }
            this.InvokeAsync("GetWOSnRule", new object[] {
                        woId}, this.GetWOSnRuleOperationCompleted, userState);
        }
        
        private void OnGetWOSnRuleOperationCompleted(object arg) {
            if ((this.GetWOSnRuleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWOSnRuleCompleted(this, new GetWOSnRuleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertWipKeyParts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertWipKeyParts(tWipKeyPartTable[] lswipkeypart) {
            object[] results = this.Invoke("InsertWipKeyParts", new object[] {
                        lswipkeypart});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertWipKeyPartsAsync(tWipKeyPartTable[] lswipkeypart) {
            this.InsertWipKeyPartsAsync(lswipkeypart, null);
        }
        
        /// <remarks/>
        public void InsertWipKeyPartsAsync(tWipKeyPartTable[] lswipkeypart, object userState) {
            if ((this.InsertWipKeyPartsOperationCompleted == null)) {
                this.InsertWipKeyPartsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertWipKeyPartsOperationCompleted);
            }
            this.InvokeAsync("InsertWipKeyParts", new object[] {
                        lswipkeypart}, this.InsertWipKeyPartsOperationCompleted, userState);
        }
        
        private void OnInsertWipKeyPartsOperationCompleted(object arg) {
            if ((this.InsertWipKeyPartsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertWipKeyPartsCompleted(this, new InsertWipKeyPartsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetEsnDataInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetEsnDataInfo(string sntype, string snval) {
            object[] results = this.Invoke("GetEsnDataInfo", new object[] {
                        sntype,
                        snval});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetEsnDataInfoAsync(string sntype, string snval) {
            this.GetEsnDataInfoAsync(sntype, snval, null);
        }
        
        /// <remarks/>
        public void GetEsnDataInfoAsync(string sntype, string snval, object userState) {
            if ((this.GetEsnDataInfoOperationCompleted == null)) {
                this.GetEsnDataInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEsnDataInfoOperationCompleted);
            }
            this.InvokeAsync("GetEsnDataInfo", new object[] {
                        sntype,
                        snval}, this.GetEsnDataInfoOperationCompleted, userState);
        }
        
        private void OnGetEsnDataInfoOperationCompleted(object arg) {
            if ((this.GetEsnDataInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEsnDataInfoCompleted(this, new GetEsnDataInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSnInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSnInfo(string serial) {
            object[] results = this.Invoke("GetSnInfo", new object[] {
                        serial});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSnInfoAsync(string serial) {
            this.GetSnInfoAsync(serial, null);
        }
        
        /// <remarks/>
        public void GetSnInfoAsync(string serial, object userState) {
            if ((this.GetSnInfoOperationCompleted == null)) {
                this.GetSnInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSnInfoOperationCompleted);
            }
            this.InvokeAsync("GetSnInfo", new object[] {
                        serial}, this.GetSnInfoOperationCompleted, userState);
        }
        
        private void OnGetSnInfoOperationCompleted(object arg) {
            if ((this.GetSnInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSnInfoCompleted(this, new GetSnInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class tWipKeyPartTable {
        
        private string idxField;
        
        private string esnField;
        
        private string woIdField;
        
        private string sntypeField;
        
        private string snvalField;
        
        private string recdateField;
        
        /// <remarks/>
        public string idx {
            get {
                return this.idxField;
            }
            set {
                this.idxField = value;
            }
        }
        
        /// <remarks/>
        public string esn {
            get {
                return this.esnField;
            }
            set {
                this.esnField = value;
            }
        }
        
        /// <remarks/>
        public string woId {
            get {
                return this.woIdField;
            }
            set {
                this.woIdField = value;
            }
        }
        
        /// <remarks/>
        public string sntype {
            get {
                return this.sntypeField;
            }
            set {
                this.sntypeField = value;
            }
        }
        
        /// <remarks/>
        public string snval {
            get {
                return this.snvalField;
            }
            set {
                this.snvalField = value;
            }
        }
        
        /// <remarks/>
        public string recdate {
            get {
                return this.recdateField;
            }
            set {
                this.recdateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CheckEmpCompletedEventHandler(object sender, CheckEmpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckEmpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckEmpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllStationCompletedEventHandler(object sender, GetAllStationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllStationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllStationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Check_Route_ATECompletedEventHandler(object sender, Check_Route_ATECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Check_Route_ATECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Check_Route_ATECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void INS_ATE_BackCompletedEventHandler(object sender, INS_ATE_BackCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class INS_ATE_BackCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal INS_ATE_BackCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetLineListCompletedEventHandler(object sender, GetLineListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLineListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLineListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetWOSnRuleCompletedEventHandler(object sender, GetWOSnRuleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWOSnRuleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWOSnRuleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InsertWipKeyPartsCompletedEventHandler(object sender, InsertWipKeyPartsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertWipKeyPartsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertWipKeyPartsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetEsnDataInfoCompletedEventHandler(object sender, GetEsnDataInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEsnDataInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEsnDataInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSnInfoCompletedEventHandler(object sender, GetSnInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSnInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSnInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591