//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWeserver.WMS_SapConnector {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZMM_GOODSMVT_CREATE", Namespace="http://schemas.datacontract.org/2004/07/Entity")]
    [System.SerializableAttribute()]
    public partial class ZMM_GOODSMVT_CREATE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DELIV_ITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DELIV_NUMBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOC_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENTRY_QNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ENTRY_UOMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ITEM_TEXTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_GOACTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string I_REFDOCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MATERIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOVE_PLANTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOVE_REASField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOVE_STLOCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOVE_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MVT_INDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NO_MORE_GRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ORDERIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PLANTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_ITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_NUMBERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PSTNG_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RESERV_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RES_ITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SALES_ORDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SPEC_STOCKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STCK_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STGE_LOCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string S_ORD_ITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UNLOAD_PTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VENDORField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DELIV_ITEM {
            get {
                return this.DELIV_ITEMField;
            }
            set {
                if ((object.ReferenceEquals(this.DELIV_ITEMField, value) != true)) {
                    this.DELIV_ITEMField = value;
                    this.RaisePropertyChanged("DELIV_ITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DELIV_NUMB {
            get {
                return this.DELIV_NUMBField;
            }
            set {
                if ((object.ReferenceEquals(this.DELIV_NUMBField, value) != true)) {
                    this.DELIV_NUMBField = value;
                    this.RaisePropertyChanged("DELIV_NUMB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOC_DATE {
            get {
                return this.DOC_DATEField;
            }
            set {
                if ((object.ReferenceEquals(this.DOC_DATEField, value) != true)) {
                    this.DOC_DATEField = value;
                    this.RaisePropertyChanged("DOC_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENTRY_QNT {
            get {
                return this.ENTRY_QNTField;
            }
            set {
                if ((object.ReferenceEquals(this.ENTRY_QNTField, value) != true)) {
                    this.ENTRY_QNTField = value;
                    this.RaisePropertyChanged("ENTRY_QNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ENTRY_UOM {
            get {
                return this.ENTRY_UOMField;
            }
            set {
                if ((object.ReferenceEquals(this.ENTRY_UOMField, value) != true)) {
                    this.ENTRY_UOMField = value;
                    this.RaisePropertyChanged("ENTRY_UOM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ITEM_TEXT {
            get {
                return this.ITEM_TEXTField;
            }
            set {
                if ((object.ReferenceEquals(this.ITEM_TEXTField, value) != true)) {
                    this.ITEM_TEXTField = value;
                    this.RaisePropertyChanged("ITEM_TEXT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string I_GOACTION {
            get {
                return this.I_GOACTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.I_GOACTIONField, value) != true)) {
                    this.I_GOACTIONField = value;
                    this.RaisePropertyChanged("I_GOACTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string I_REFDOC {
            get {
                return this.I_REFDOCField;
            }
            set {
                if ((object.ReferenceEquals(this.I_REFDOCField, value) != true)) {
                    this.I_REFDOCField = value;
                    this.RaisePropertyChanged("I_REFDOC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MATERIAL {
            get {
                return this.MATERIALField;
            }
            set {
                if ((object.ReferenceEquals(this.MATERIALField, value) != true)) {
                    this.MATERIALField = value;
                    this.RaisePropertyChanged("MATERIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOVE_PLANT {
            get {
                return this.MOVE_PLANTField;
            }
            set {
                if ((object.ReferenceEquals(this.MOVE_PLANTField, value) != true)) {
                    this.MOVE_PLANTField = value;
                    this.RaisePropertyChanged("MOVE_PLANT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOVE_REAS {
            get {
                return this.MOVE_REASField;
            }
            set {
                if ((object.ReferenceEquals(this.MOVE_REASField, value) != true)) {
                    this.MOVE_REASField = value;
                    this.RaisePropertyChanged("MOVE_REAS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOVE_STLOC {
            get {
                return this.MOVE_STLOCField;
            }
            set {
                if ((object.ReferenceEquals(this.MOVE_STLOCField, value) != true)) {
                    this.MOVE_STLOCField = value;
                    this.RaisePropertyChanged("MOVE_STLOC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOVE_TYPE {
            get {
                return this.MOVE_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.MOVE_TYPEField, value) != true)) {
                    this.MOVE_TYPEField = value;
                    this.RaisePropertyChanged("MOVE_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MVT_IND {
            get {
                return this.MVT_INDField;
            }
            set {
                if ((object.ReferenceEquals(this.MVT_INDField, value) != true)) {
                    this.MVT_INDField = value;
                    this.RaisePropertyChanged("MVT_IND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NO_MORE_GR {
            get {
                return this.NO_MORE_GRField;
            }
            set {
                if ((object.ReferenceEquals(this.NO_MORE_GRField, value) != true)) {
                    this.NO_MORE_GRField = value;
                    this.RaisePropertyChanged("NO_MORE_GR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ORDERID {
            get {
                return this.ORDERIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ORDERIDField, value) != true)) {
                    this.ORDERIDField = value;
                    this.RaisePropertyChanged("ORDERID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PLANT {
            get {
                return this.PLANTField;
            }
            set {
                if ((object.ReferenceEquals(this.PLANTField, value) != true)) {
                    this.PLANTField = value;
                    this.RaisePropertyChanged("PLANT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_ITEM {
            get {
                return this.PO_ITEMField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_ITEMField, value) != true)) {
                    this.PO_ITEMField = value;
                    this.RaisePropertyChanged("PO_ITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PO_NUMBER {
            get {
                return this.PO_NUMBERField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_NUMBERField, value) != true)) {
                    this.PO_NUMBERField = value;
                    this.RaisePropertyChanged("PO_NUMBER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PSTNG_DATE {
            get {
                return this.PSTNG_DATEField;
            }
            set {
                if ((object.ReferenceEquals(this.PSTNG_DATEField, value) != true)) {
                    this.PSTNG_DATEField = value;
                    this.RaisePropertyChanged("PSTNG_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RESERV_NO {
            get {
                return this.RESERV_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.RESERV_NOField, value) != true)) {
                    this.RESERV_NOField = value;
                    this.RaisePropertyChanged("RESERV_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RES_ITEM {
            get {
                return this.RES_ITEMField;
            }
            set {
                if ((object.ReferenceEquals(this.RES_ITEMField, value) != true)) {
                    this.RES_ITEMField = value;
                    this.RaisePropertyChanged("RES_ITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SALES_ORD {
            get {
                return this.SALES_ORDField;
            }
            set {
                if ((object.ReferenceEquals(this.SALES_ORDField, value) != true)) {
                    this.SALES_ORDField = value;
                    this.RaisePropertyChanged("SALES_ORD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SPEC_STOCK {
            get {
                return this.SPEC_STOCKField;
            }
            set {
                if ((object.ReferenceEquals(this.SPEC_STOCKField, value) != true)) {
                    this.SPEC_STOCKField = value;
                    this.RaisePropertyChanged("SPEC_STOCK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STCK_TYPE {
            get {
                return this.STCK_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.STCK_TYPEField, value) != true)) {
                    this.STCK_TYPEField = value;
                    this.RaisePropertyChanged("STCK_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string STGE_LOC {
            get {
                return this.STGE_LOCField;
            }
            set {
                if ((object.ReferenceEquals(this.STGE_LOCField, value) != true)) {
                    this.STGE_LOCField = value;
                    this.RaisePropertyChanged("STGE_LOC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string S_ORD_ITEM {
            get {
                return this.S_ORD_ITEMField;
            }
            set {
                if ((object.ReferenceEquals(this.S_ORD_ITEMField, value) != true)) {
                    this.S_ORD_ITEMField = value;
                    this.RaisePropertyChanged("S_ORD_ITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UNLOAD_PT {
            get {
                return this.UNLOAD_PTField;
            }
            set {
                if ((object.ReferenceEquals(this.UNLOAD_PTField, value) != true)) {
                    this.UNLOAD_PTField = value;
                    this.RaisePropertyChanged("UNLOAD_PT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VENDOR {
            get {
                return this.VENDORField;
            }
            set {
                if ((object.ReferenceEquals(this.VENDORField, value) != true)) {
                    this.VENDORField = value;
                    this.RaisePropertyChanged("VENDOR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WMS_SapConnector.ISapConnector")]
    public interface ISapConnector {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/GetErrorMsg", ReplyAction="http://tempuri.org/ISapConnector/GetErrorMsgResponse")]
        string GetErrorMsg();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/Get_Z_RFC_ZMM011", ReplyAction="http://tempuri.org/ISapConnector/Get_Z_RFC_ZMM011Response")]
        byte[] Get_Z_RFC_ZMM011(string woid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/Get_Z_RFC_ZMM011_WinCE", ReplyAction="http://tempuri.org/ISapConnector/Get_Z_RFC_ZMM011_WinCEResponse")]
        byte[] Get_Z_RFC_ZMM011_WinCE(string woid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/Get_Z_RFC_AFPO", ReplyAction="http://tempuri.org/ISapConnector/Get_Z_RFC_AFPOResponse")]
        byte[] Get_Z_RFC_AFPO(string woid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/Get_Z_RFC_ZPP007", ReplyAction="http://tempuri.org/ISapConnector/Get_Z_RFC_ZPP007Response")]
        byte[] Get_Z_RFC_ZPP007(string partNumber, string facCode, string strDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/Get_Z_RFC_LIPS", ReplyAction="http://tempuri.org/ISapConnector/Get_Z_RFC_LIPSResponse")]
        byte[] Get_Z_RFC_LIPS(string PVBELN, string MJAHR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/Get_Z_RFC_MSEG", ReplyAction="http://tempuri.org/ISapConnector/Get_Z_RFC_MSEGResponse")]
        byte[] Get_Z_RFC_MSEG(string IMBLNR, string MJAHR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/Get_Z_RFC_PO", ReplyAction="http://tempuri.org/ISapConnector/Get_Z_RFC_POResponse")]
        byte[] Get_Z_RFC_PO(string EBELN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/Get_Z_RFC_GD_DELIVERY", ReplyAction="http://tempuri.org/ISapConnector/Get_Z_RFC_GD_DELIVERYResponse")]
        string[] Get_Z_RFC_GD_DELIVERY(string I_VBELN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/Get_Z_RFC_ZWMSMM001", ReplyAction="http://tempuri.org/ISapConnector/Get_Z_RFC_ZWMSMM001Response")]
        string Get_Z_RFC_ZWMSMM001(out string _ErrStr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/Get_R_MSEG", ReplyAction="http://tempuri.org/ISapConnector/Get_R_MSEGResponse")]
        byte[] Get_R_MSEG(string QC_NO, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/Get_R_SAPPI", ReplyAction="http://tempuri.org/ISapConnector/Get_R_SAPPIResponse")]
        byte[] Get_R_SAPPI(string QC_NO, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/RFC_ZMM_GOODSMVT_CREATE", ReplyAction="http://tempuri.org/ISapConnector/RFC_ZMM_GOODSMVT_CREATEResponse")]
        byte[] RFC_ZMM_GOODSMVT_CREATE(TestWeserver.WMS_SapConnector.ZMM_GOODSMVT_CREATE zgc, string remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/RFC_ZMM_RESERVATION_GETDETAIL", ReplyAction="http://tempuri.org/ISapConnector/RFC_ZMM_RESERVATION_GETDETAILResponse")]
        byte[] RFC_ZMM_RESERVATION_GETDETAIL(string I_RESERVATION);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/RFC_ZMM_OUTBOUND_DELIVERY_GETLIST", ReplyAction="http://tempuri.org/ISapConnector/RFC_ZMM_OUTBOUND_DELIVERY_GETLISTResponse")]
        byte[] RFC_ZMM_OUTBOUND_DELIVERY_GETLIST(string I_VBELN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/RFC_ZMM_OUTBOUND_DELIVERY_POST", ReplyAction="http://tempuri.org/ISapConnector/RFC_ZMM_OUTBOUND_DELIVERY_POSTResponse")]
        string[] RFC_ZMM_OUTBOUND_DELIVERY_POST(System.Collections.Generic.Dictionary<string, object>[] dicList, string I_VBELN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/RFC_ZMM_GOODSMVT_CREATE_list", ReplyAction="http://tempuri.org/ISapConnector/RFC_ZMM_GOODSMVT_CREATE_listResponse")]
        byte[] RFC_ZMM_GOODSMVT_CREATE_list(System.Collections.Generic.Dictionary<string, object>[] dicList, string remark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/RFC_ZppUsage_OUT", ReplyAction="http://tempuri.org/ISapConnector/RFC_ZppUsage_OUTResponse")]
        byte[] RFC_ZppUsage_OUT(string IQC_No, string V_CODE, string V_CODEGRP, string V_MENGE01, string QLGO_VM01, string V_MENGE04, string QLGO_VM04, string V_MENGE07);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapConnector/RFC_ZMM_GOODSMVT_CREATE_JSON", ReplyAction="http://tempuri.org/ISapConnector/RFC_ZMM_GOODSMVT_CREATE_JSONResponse")]
        byte[] RFC_ZMM_GOODSMVT_CREATE_JSON(string ListJsonStr, string remark);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISapConnectorChannel : TestWeserver.WMS_SapConnector.ISapConnector, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SapConnectorClient : System.ServiceModel.ClientBase<TestWeserver.WMS_SapConnector.ISapConnector>, TestWeserver.WMS_SapConnector.ISapConnector {
        
        public SapConnectorClient() {
        }
        
        public SapConnectorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SapConnectorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SapConnectorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SapConnectorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetErrorMsg() {
            return base.Channel.GetErrorMsg();
        }
        
        public byte[] Get_Z_RFC_ZMM011(string woid) {
            return base.Channel.Get_Z_RFC_ZMM011(woid);
        }
        
        public byte[] Get_Z_RFC_ZMM011_WinCE(string woid) {
            return base.Channel.Get_Z_RFC_ZMM011_WinCE(woid);
        }
        
        public byte[] Get_Z_RFC_AFPO(string woid) {
            return base.Channel.Get_Z_RFC_AFPO(woid);
        }
        
        public byte[] Get_Z_RFC_ZPP007(string partNumber, string facCode, string strDate) {
            return base.Channel.Get_Z_RFC_ZPP007(partNumber, facCode, strDate);
        }
        
        public byte[] Get_Z_RFC_LIPS(string PVBELN, string MJAHR) {
            return base.Channel.Get_Z_RFC_LIPS(PVBELN, MJAHR);
        }
        
        public byte[] Get_Z_RFC_MSEG(string IMBLNR, string MJAHR) {
            return base.Channel.Get_Z_RFC_MSEG(IMBLNR, MJAHR);
        }
        
        public byte[] Get_Z_RFC_PO(string EBELN) {
            return base.Channel.Get_Z_RFC_PO(EBELN);
        }
        
        public string[] Get_Z_RFC_GD_DELIVERY(string I_VBELN) {
            return base.Channel.Get_Z_RFC_GD_DELIVERY(I_VBELN);
        }
        
        public string Get_Z_RFC_ZWMSMM001(out string _ErrStr) {
            return base.Channel.Get_Z_RFC_ZWMSMM001(out _ErrStr);
        }
        
        public byte[] Get_R_MSEG(string QC_NO, string year) {
            return base.Channel.Get_R_MSEG(QC_NO, year);
        }
        
        public byte[] Get_R_SAPPI(string QC_NO, string year) {
            return base.Channel.Get_R_SAPPI(QC_NO, year);
        }
        
        public byte[] RFC_ZMM_GOODSMVT_CREATE(TestWeserver.WMS_SapConnector.ZMM_GOODSMVT_CREATE zgc, string remark) {
            return base.Channel.RFC_ZMM_GOODSMVT_CREATE(zgc, remark);
        }
        
        public byte[] RFC_ZMM_RESERVATION_GETDETAIL(string I_RESERVATION) {
            return base.Channel.RFC_ZMM_RESERVATION_GETDETAIL(I_RESERVATION);
        }
        
        public byte[] RFC_ZMM_OUTBOUND_DELIVERY_GETLIST(string I_VBELN) {
            return base.Channel.RFC_ZMM_OUTBOUND_DELIVERY_GETLIST(I_VBELN);
        }
        
        public string[] RFC_ZMM_OUTBOUND_DELIVERY_POST(System.Collections.Generic.Dictionary<string, object>[] dicList, string I_VBELN) {
            return base.Channel.RFC_ZMM_OUTBOUND_DELIVERY_POST(dicList, I_VBELN);
        }
        
        public byte[] RFC_ZMM_GOODSMVT_CREATE_list(System.Collections.Generic.Dictionary<string, object>[] dicList, string remark) {
            return base.Channel.RFC_ZMM_GOODSMVT_CREATE_list(dicList, remark);
        }
        
        public byte[] RFC_ZppUsage_OUT(string IQC_No, string V_CODE, string V_CODEGRP, string V_MENGE01, string QLGO_VM01, string V_MENGE04, string QLGO_VM04, string V_MENGE07) {
            return base.Channel.RFC_ZppUsage_OUT(IQC_No, V_CODE, V_CODEGRP, V_MENGE01, QLGO_VM01, V_MENGE04, QLGO_VM04, V_MENGE07);
        }
        
        public byte[] RFC_ZMM_GOODSMVT_CREATE_JSON(string ListJsonStr, string remark) {
            return base.Channel.RFC_ZMM_GOODSMVT_CREATE_JSON(ListJsonStr, remark);
        }
    }
}
