//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5456
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.5456 版自动生成。
// 
#pragma warning disable 1591

namespace SFIS_DCT_V2.PublicStro {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="tPublicStoredprocSoap", Namespace="http://tempuri.org/")]
    public partial class tPublicStoredproc : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback SP_PublicStoredprocOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListStationTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStoredprocValuesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSystemInputDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShowMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLineListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllStationOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWoListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStockInNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSystemStoredprocOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public tPublicStoredproc() {
            this.Url = global::SFIS_DCT_V2.Properties.Settings.Default.SFIS_DCT_V2_PublicStro_tPublicStoredproc;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event SP_PublicStoredprocCompletedEventHandler SP_PublicStoredprocCompleted;
        
        /// <remarks/>
        public event GetListStationTypeCompletedEventHandler GetListStationTypeCompleted;
        
        /// <remarks/>
        public event GetStoredprocValuesCompletedEventHandler GetStoredprocValuesCompleted;
        
        /// <remarks/>
        public event GetSystemInputDataCompletedEventHandler GetSystemInputDataCompleted;
        
        /// <remarks/>
        public event GetShowMessageCompletedEventHandler GetShowMessageCompleted;
        
        /// <remarks/>
        public event GetLineListCompletedEventHandler GetLineListCompleted;
        
        /// <remarks/>
        public event GetAllStationCompletedEventHandler GetAllStationCompleted;
        
        /// <remarks/>
        public event GetWoListCompletedEventHandler GetWoListCompleted;
        
        /// <remarks/>
        public event GetStockInNumberCompletedEventHandler GetStockInNumberCompleted;
        
        /// <remarks/>
        public event GetSystemStoredprocCompletedEventHandler GetSystemStoredprocCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SP_PublicStoredproc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SP_PublicStoredproc(string Storedproc, System.Data.DataTable dt) {
            object[] results = this.Invoke("SP_PublicStoredproc", new object[] {
                        Storedproc,
                        dt});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SP_PublicStoredprocAsync(string Storedproc, System.Data.DataTable dt) {
            this.SP_PublicStoredprocAsync(Storedproc, dt, null);
        }
        
        /// <remarks/>
        public void SP_PublicStoredprocAsync(string Storedproc, System.Data.DataTable dt, object userState) {
            if ((this.SP_PublicStoredprocOperationCompleted == null)) {
                this.SP_PublicStoredprocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSP_PublicStoredprocOperationCompleted);
            }
            this.InvokeAsync("SP_PublicStoredproc", new object[] {
                        Storedproc,
                        dt}, this.SP_PublicStoredprocOperationCompleted, userState);
        }
        
        private void OnSP_PublicStoredprocOperationCompleted(object arg) {
            if ((this.SP_PublicStoredprocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SP_PublicStoredprocCompleted(this, new SP_PublicStoredprocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListStationType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetListStationType() {
            object[] results = this.Invoke("GetListStationType", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetListStationTypeAsync() {
            this.GetListStationTypeAsync(null);
        }
        
        /// <remarks/>
        public void GetListStationTypeAsync(object userState) {
            if ((this.GetListStationTypeOperationCompleted == null)) {
                this.GetListStationTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListStationTypeOperationCompleted);
            }
            this.InvokeAsync("GetListStationType", new object[0], this.GetListStationTypeOperationCompleted, userState);
        }
        
        private void OnGetListStationTypeOperationCompleted(object arg) {
            if ((this.GetListStationTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListStationTypeCompleted(this, new GetListStationTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStoredprocValues", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetStoredprocValues(string Pro) {
            object[] results = this.Invoke("GetStoredprocValues", new object[] {
                        Pro});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetStoredprocValuesAsync(string Pro) {
            this.GetStoredprocValuesAsync(Pro, null);
        }
        
        /// <remarks/>
        public void GetStoredprocValuesAsync(string Pro, object userState) {
            if ((this.GetStoredprocValuesOperationCompleted == null)) {
                this.GetStoredprocValuesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStoredprocValuesOperationCompleted);
            }
            this.InvokeAsync("GetStoredprocValues", new object[] {
                        Pro}, this.GetStoredprocValuesOperationCompleted, userState);
        }
        
        private void OnGetStoredprocValuesOperationCompleted(object arg) {
            if ((this.GetStoredprocValuesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStoredprocValuesCompleted(this, new GetStoredprocValuesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSystemInputData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSystemInputData() {
            object[] results = this.Invoke("GetSystemInputData", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSystemInputDataAsync() {
            this.GetSystemInputDataAsync(null);
        }
        
        /// <remarks/>
        public void GetSystemInputDataAsync(object userState) {
            if ((this.GetSystemInputDataOperationCompleted == null)) {
                this.GetSystemInputDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSystemInputDataOperationCompleted);
            }
            this.InvokeAsync("GetSystemInputData", new object[0], this.GetSystemInputDataOperationCompleted, userState);
        }
        
        private void OnGetSystemInputDataOperationCompleted(object arg) {
            if ((this.GetSystemInputDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSystemInputDataCompleted(this, new GetSystemInputDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetShowMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetShowMessage(string StationId) {
            object[] results = this.Invoke("GetShowMessage", new object[] {
                        StationId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetShowMessageAsync(string StationId) {
            this.GetShowMessageAsync(StationId, null);
        }
        
        /// <remarks/>
        public void GetShowMessageAsync(string StationId, object userState) {
            if ((this.GetShowMessageOperationCompleted == null)) {
                this.GetShowMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShowMessageOperationCompleted);
            }
            this.InvokeAsync("GetShowMessage", new object[] {
                        StationId}, this.GetShowMessageOperationCompleted, userState);
        }
        
        private void OnGetShowMessageOperationCompleted(object arg) {
            if ((this.GetShowMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShowMessageCompleted(this, new GetShowMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLineList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetLineList() {
            object[] results = this.Invoke("GetLineList", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetLineListAsync() {
            this.GetLineListAsync(null);
        }
        
        /// <remarks/>
        public void GetLineListAsync(object userState) {
            if ((this.GetLineListOperationCompleted == null)) {
                this.GetLineListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLineListOperationCompleted);
            }
            this.InvokeAsync("GetLineList", new object[0], this.GetLineListOperationCompleted, userState);
        }
        
        private void OnGetLineListOperationCompleted(object arg) {
            if ((this.GetLineListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLineListCompleted(this, new GetLineListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllStation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllStation(string woId) {
            object[] results = this.Invoke("GetAllStation", new object[] {
                        woId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllStationAsync(string woId) {
            this.GetAllStationAsync(woId, null);
        }
        
        /// <remarks/>
        public void GetAllStationAsync(string woId, object userState) {
            if ((this.GetAllStationOperationCompleted == null)) {
                this.GetAllStationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllStationOperationCompleted);
            }
            this.InvokeAsync("GetAllStation", new object[] {
                        woId}, this.GetAllStationOperationCompleted, userState);
        }
        
        private void OnGetAllStationOperationCompleted(object arg) {
            if ((this.GetAllStationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllStationCompleted(this, new GetAllStationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetWoList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetWoList() {
            object[] results = this.Invoke("GetWoList", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetWoListAsync() {
            this.GetWoListAsync(null);
        }
        
        /// <remarks/>
        public void GetWoListAsync(object userState) {
            if ((this.GetWoListOperationCompleted == null)) {
                this.GetWoListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWoListOperationCompleted);
            }
            this.InvokeAsync("GetWoList", new object[0], this.GetWoListOperationCompleted, userState);
        }
        
        private void OnGetWoListOperationCompleted(object arg) {
            if ((this.GetWoListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWoListCompleted(this, new GetWoListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStockInNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetStockInNumber() {
            object[] results = this.Invoke("GetStockInNumber", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStockInNumberAsync() {
            this.GetStockInNumberAsync(null);
        }
        
        /// <remarks/>
        public void GetStockInNumberAsync(object userState) {
            if ((this.GetStockInNumberOperationCompleted == null)) {
                this.GetStockInNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStockInNumberOperationCompleted);
            }
            this.InvokeAsync("GetStockInNumber", new object[0], this.GetStockInNumberOperationCompleted, userState);
        }
        
        private void OnGetStockInNumberOperationCompleted(object arg) {
            if ((this.GetStockInNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStockInNumberCompleted(this, new GetStockInNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSystemStoredproc", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetSystemStoredproc(int StationId) {
            object[] results = this.Invoke("GetSystemStoredproc", new object[] {
                        StationId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetSystemStoredprocAsync(int StationId) {
            this.GetSystemStoredprocAsync(StationId, null);
        }
        
        /// <remarks/>
        public void GetSystemStoredprocAsync(int StationId, object userState) {
            if ((this.GetSystemStoredprocOperationCompleted == null)) {
                this.GetSystemStoredprocOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSystemStoredprocOperationCompleted);
            }
            this.InvokeAsync("GetSystemStoredproc", new object[] {
                        StationId}, this.GetSystemStoredprocOperationCompleted, userState);
        }
        
        private void OnGetSystemStoredprocOperationCompleted(object arg) {
            if ((this.GetSystemStoredprocCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSystemStoredprocCompleted(this, new GetSystemStoredprocCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void SP_PublicStoredprocCompletedEventHandler(object sender, SP_PublicStoredprocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SP_PublicStoredprocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SP_PublicStoredprocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetListStationTypeCompletedEventHandler(object sender, GetListStationTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListStationTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListStationTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetStoredprocValuesCompletedEventHandler(object sender, GetStoredprocValuesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStoredprocValuesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStoredprocValuesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetSystemInputDataCompletedEventHandler(object sender, GetSystemInputDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSystemInputDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSystemInputDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetShowMessageCompletedEventHandler(object sender, GetShowMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShowMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShowMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetLineListCompletedEventHandler(object sender, GetLineListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLineListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLineListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetAllStationCompletedEventHandler(object sender, GetAllStationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllStationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllStationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetWoListCompletedEventHandler(object sender, GetWoListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWoListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWoListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetStockInNumberCompletedEventHandler(object sender, GetStockInNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStockInNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStockInNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    public delegate void GetSystemStoredprocCompletedEventHandler(object sender, GetSystemStoredprocCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5420")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSystemStoredprocCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSystemStoredprocCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591